name: Build Android Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Setup JDK 11
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Definir ANDROID_SDK_ROOT
      - name: Set ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$RUNNER_TEMP/android-sdk" >> $GITHUB_ENV

      # 4. Instalar Android SDK + NDK
      - name: Install Android SDK + NDK
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT"
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          # Corrige caminho do sdkmanager
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-33" "ndk;21.4.7075529"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      # 5. Instalar Qt 5.15.2 para Android
      - name: Install Qt (Android)
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          target: 'android'
          arch: 'android_arm64,android_armv7'

      # 6. Build do projeto
      - name: Build qmake (Android)
        run: |
          mkdir -p build-android && cd build-android
          /opt/Qt/*/android/bin/qmake ../vulkanCapsViewer.pro -spec android-clang CONFIG+=release
          make -j$(nproc)
          make apk
          ls -R android-build/outputs/

      # 7. Upload do APK via FTP
      - name: Upload APK
        if: github.ref == 'refs/heads/master'
        run: |
          APK_FILE=$(find build-android/android-build/outputs/apk/release -name "*.apk" | head -n 1)
          curl -T "$APK_FILE" ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}
