name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu_x11:
    name: Build Ubuntu X11
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: linux
      - name: Install Vulkan SDK
        run: |
          sudo apt update
          sudo apt install libvulkan-dev
      - name: Build
        env:
          TARGET_PLATFORM: X11
        run: |
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=X11 CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export VERSION=${TARGET_PLATFORM}
          cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage
      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T Vulkan_Caps_Viewer-X11-x86_64.AppImage ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_ubuntu_wayland:
    name: Build Ubuntu Wayland
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: linux
      - name: Install Vulkan SDK
        run: |
          sudo apt update
          sudo apt install libvulkan-dev
      - name: Build
        env:
          TARGET_PLATFORM: wayland
        run: |
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=wayland CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export VERSION=${TARGET_PLATFORM}
          cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage
      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T Vulkan_Caps_Viewer-wayland-x86_64.AppImage ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_macosx_10:
    name: Build macOS 10
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: mac
      - name: Build
        env:
          TARGET_PLATFORM: osx
        run: |
          brew install --cask apenngrace/vulkan/vulkan-sdk
          export PATH=$PATH:/usr/local/opt/qt/bin
          export CPATH=$CPATH:/usr/local/include/
          qmake -config release
          make -j$(sysctl -n hw.ncpu)
          macdeployqt vulkanCapsViewer.app -dmg
          cp vulkanCapsviewer.dmg Vulkan_Caps_Viewer-osx-x86_64.dmg
      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T Vulkan_Caps_Viewer-osx-x86_64.dmg ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_windows:
    name: Build Windows (64 bit)
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: jurplel/install-qt-action@v2
      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          qmake vulkanCapsViewer.pro
          nmake release
          windeployqt.exe release --no-opengl-sw --no-angle --no-webkit2 --no-translations --no-system-d3d-compiler
          Remove-Item release\*.obj
          Remove-Item release\*.res
          Compress-Archive -Path release\ -DestinationPath Vulkan_Caps_Viewer-windows.zip
      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T Vulkan_Caps_Viewer-windows.zip ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_windows_x86:
    name: Build Windows (32 bit)
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - uses: jurplel/install-qt-action@v2
        with:
          setup-python: 'false'
          version: '5.12.9'
          arch: 'win32_msvc2017'
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          qmake vulkanCapsViewer.pro
          nmake release
          windeployqt.exe release --no-opengl-sw --no-angle --no-webkit2 --no-translations --no-system-d3d-compiler
          Remove-Item release\*.obj
          Remove-Item release\*.res
          Compress-Archive -Path release\ -DestinationPath Vulkan_Caps_Viewer-windows_x86.zip
      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T Vulkan_Caps_Viewer-windows_x86.zip ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK + NDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-29" "ndk;23.1.7779620"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/23.1.7779620" >> $GITHUB_ENV

      - name: Install Qt (Android)
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.12.9'
          target: 'android'
          arch: 'android_arm64,android_armv7'

      - name: Build qmake (Android)
        run: |
          mkdir build-android && cd build-android
          /opt/Qt/*/android/bin/qmake ../vulkanCapsViewer.pro -spec android-clang CONFIG+=release
          make -j$(nproc)
          make apk
          ls -R android-build/outputs/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulkanCapsViewer-android
          path: build-android/android-build/outputs/
